### PR TITLE
refactor/class c to enum

### PR DESCRIPTION
**Pull request by victortive**
There are many uses of the class C that holds constants that can be represented by enums instead.

For example the RTCSessionState can be converted to this:

```dart
class C {
  // RTCSession states.
  static const int STATUS_NULL = 0;
  static const int STATUS_INVITE_SENT = 1;
  static const int STATUS_1XX_RECEIVED = 2;
  static const int STATUS_INVITE_RECEIVED = 3;
  static const int STATUS_WAITING_FOR_ANSWER = 4;
  static const int STATUS_ANSWERED = 5;
  static const int STATUS_WAITING_FOR_ACK = 6;
  static const int STATUS_CANCELED = 7;
  static const int STATUS_TERMINATED = 8;
  static const int STATUS_CONFIRMED = 9;
}
```

to this

```dart
enum RtcSessionState {
  none, // STATUS_NULL
  inviteSent, // STATUS_INVITE_SENT
  provisionalResponse, // STATUS_1XX_RECEIVED
  inviteReceived, // STATUS_INVITE_RECEIVED
  waitingForAnswer, // STATUS_WAITING_FOR_ANSWER
  answered, // STATUS_ANSWERED
  waitingForAck, // STATUS_WAITING_FOR_ACK
  canceled, // STATUS_CANCELED
  terminated, // STATUS_TERMINATED
  confirmed, // STATUS_CONFIRMED
}
```

### CODE REVIEW

**Comment by mikaelwills** [comment]
@victortive  love this, rebase and fix up the conflicts and we'll be good to go.

**Comment by victortive** [comment]
@mikaelwills What conflicts are you referring to?

**Comment by mikaelwills** [comment]
@victortive Just below our comments "this branch cannot be rebased due to conflict"

**Comment by mikaelwills** [comment]
@victortive  merged in and it passed all the build checks, looking good!
Im sure you've done some already but will give it an integration test with two clients to make sure all is well.

**Pull request merged**
