### PR TITLE
migrate to null safety

### PR DESCRIPTION
**Pull request by viplifes**
I have updated all project files to support null safety.
This merge still needs to be checked and tested for errors. 
But the project is already started and running.

### CODE REVIEW

**Comment by cloudwebrtc** [comment]
Hey @viplifes, thanks a lot 👍 .  can you resolve the conflict? It seems to be caused by a different fork

**Comment by viplifes** [comment]
Conflicts have been resolved.

**Comment by AlvaroVasconcelos** [comment]
@viplifes bug on hangup
image

**Comment by viplifes** [comment]
Thanks, fixed. You can upgrade and try again.

**Comment by AlvaroVasconcelos** [comment]
Solved, thank you!

**Review by elbysamsonleader — APPROVED** [review]

**Comment by jongerenchaos** [comment]
@viplifes on registering with the demo app i get the error:

I/flutter (15018): [2022-02-02 15:18:30.675] Level.error event_manager.dart:110 ::: type 'Null' is not a subtype of type 'bool'
I/flutter (15018): #0      new Challenge.fromMap (package:sip_ua/src/digest_authentication.dart:10:27)
I/flutter (15018): #1      RequestSender._receiveResponse (package:sip_ua/src/request_sender.dart:122:23)
I/flutter (15018): #2      RequestSender.send.<anonymous closure> (package:sip_ua/src/request_sender.dart:57:7)
I/flutter (15018): #3      EventManager.emit.<anonymous closure> (package:sip_ua/src/event_manager/event_manager.dart:108:17)
I/flutter (15018): #4      List.forEach (dart:core-patch/growable_array.dart:433:8)
I/flutter (15018): #5      EventManager.emit (package:sip_ua/src/event_manager/event_manager.dart:105:12)
I/flutter (15018): #6      NonInviteClientTransaction.receiveResponse (package:sip_ua/src/transactions/non_invite_client.dart:96:28)
I/flutter (15018): #7      UA.onTransportData (package:sip_ua/src/ua.dart:882:25)
I/flutter (15018): #8      Transport._onData (package:sip_ua/src/transport.dart:316:11)
I/flutter (15018): #9      WebSocketInterface._onMessage (package:sip_ua/src/transports/websocket_interface.dart:172:16)
I/flutter (15018): #10     WebSocketInterface.connect.<anonymous closure> (package:sip_ua/src/transports/websocket_interface.dart:92:9)
I/flutter (15018): #11     WebSocketImpl.co

This stops the whole registering proces. With the non null-safety version i get:

I/flutter ( 8017): [2022-02-01 11:54:30.796] Level.debug digest_authentication.dart:178 ::: authenticate() | using qop=auth [a2:REGISTER:sip:weburl.nl]
I/flutter ( 8017): [2022-02-01 11:54:30.801] Level.debug digest_authentication.dart:205 ::: authenticate() | response generated
I/flutter ( 8017): [2022-02-01 11:54:30.808] Level.debug transport.dart:168 ::: send()
I/flutter ( 8017): [2022-02-01 11:54:30.812] Level.debug websocket_interface.dart:131 ::: send()
I/flutter ( 8017): [2022-02-01 11:54:30.815] Level.debug websocket_dart_impl.dart:49 ::: send:

and after some seconds a registration succes:
I/flutter ( 8017): [2022-02-01 11:54:31.291] Level.debug sip_ua_helper.dart:144 ::: registered => Code: [200], Cause: registered, Reason: OK
I/flutter ( 8017): [2022-02-01 11:54:34.84] Level.debug websocket_interface.dart:169 ::: Received WebSocket message
I/flutter ( 8017): [2022-02-01 11:54:34.87] Level.debug websocket_interface.dart:174 ::: Received and ignored empty packet

How can we resolve this failure?

**Comment by cloudwebrtc** [comment]
@jongerenchaos I fixed this and you can test it out, so we can move this PR forward.

**Comment by jongerenchaos** [comment]
Tnx! It works without any problem!

**Pull request merged**
