### PR TITLE
replace string enum usage with dart enums

### PR DESCRIPTION
**Pull request by victortive**
- Usage of strings for the direction is confusing and inconsistent as one place uppercased the call direction.
- To make the API easier to use, I have replaced the direction with an enum

### CODE REVIEW

**Review by cloudwebrtc — APPROVED** [review]
lgtm!

Unable to merge temporarily, GitHub prompts a conflict

**Comment by victortive** [comment]
I'll look into resolving this

**Comment by mikaelwills** [comment]
@victortive  ah, just merged the other one. This one still has conflicts, follow all the git steps I mentioned in the other PR

**Comment by victortive** [comment]
> @victortive ah, just merged the other one. This one still has conflicts, follow all the git steps I mentioned in the other PR

Fixed

**Pull request merged**
